travelPages/urls.py
from django.urls import path
from .views import indexPageView, tripsPageView, detailsPageView, twitter, facebook, linkedin

app_name = 'travelPages'
urlpatterns = [
    path("", indexPageView, name="index"),
    path("trips/",tripsPageView,name="trips"),
    path("<int:id>/", detailsPageView, name='details'),
    path("twitter/",twitter,name="twitter"),
    path("facebook/",facebook,name="facebook"),
    path("linkedin/",linkedin,name="linkedin")
]

trip_me/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('travelPages.urls')),
]

travelPages/models.py
from django.db import models

# Create your models here.

class tripInfo(models.Model):

    city = models.CharField(max_length=30)
    state = models.CharField(max_length=30,null=True,blank=True)
    country = models.CharField(max_length=30)
    description = models.TextField(max_length=1000)
    length = models.IntegerField(default=0)
    cost = models.FloatField(default=0.00)
    picture = models.CharField(max_length=30)
    alt = models.CharField(max_length=100,null=True)

    def __str__(self):
        return self.location
    
    def location(self):
        return '%s %s' (self.city, self.country)

travelPages/views.py
from django.shortcuts import render, redirect
from .models import tripInfo

# Create your views here.
def indexPageView(request):
    ti = tripInfo.objects.all()

    context = {
        "ti" : ti
    }
    return render(request, 'travelPages/index.html',context)

def tripsPageView(request) :
    ti = tripInfo.objects.all()

    context = {
        "ti" : ti
    }
    return render(request, 'travelPages/trips.html',context)

def detailsPageView(request, id):

   ti=tripInfo.objects.get(id=id)

   context = {
      "ti" : ti
   }

   return render(request,'travelPages/details.html', context)

def twitter(request):
    return redirect("http://twitter.com")

def facebook(request):
    return redirect("http://facebook.com")

def linkedin(request):
    return redirect("http://linkedin.com")

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        {% block meta %}
        {% endblock %}
        <!-- Favicon-->
        <link rel="icon" type="image/png" href="{% static 'img/silhouette-palm-tree-3.png' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!--Masthead-->
                {% block Masthead %}
                {% endblock %}


        <!--Navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="{% url 'travelPages:index' %}"><img src="{% static 'img/logo.png'  %}" alt="Trip Me Travel Logo" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars ms-1"></i>
                </button>
                
                        {% block nav %}
                        {% endblock %}
                    
            </div>
        </nav>

        {% block content %}
        {% endblock %}
 <!-- Contact-->
 <section class="page-section" id="contact">
    <div class="container">
        <div class="text-center">
            <h2 class="section-heading text-uppercase">Contact Us</h2>
            <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>
        </div>
        <!-- * * * * * * * * * * * * * * *-->
        <!-- * * SB Forms Contact Form * *-->
        <!-- * * * * * * * * * * * * * * *-->
        <!-- This form is pre-integrated with SB Forms.-->
        <!-- To make this form functional, sign up at-->
        <!-- https://startbootstrap.com/solution/contact-forms-->
        <!-- to get an API token!-->
        <form id="contactForm" data-sb-form-api-token="API_TOKEN">
            <div class="row align-items-stretch mb-5">
                <div class="col-md-6">
                    <div class="form-group">
                        <!-- Name input-->
                        <input class="form-control" id="name" type="text" placeholder="Your Name *" data-sb-validations="required" />
                        <div class="invalid-feedback" data-sb-feedback="name:required">A name is required.</div>
                    </div>
                    <div class="form-group">
                        <!-- Email address input-->
                        <input class="form-control" id="email" type="email" placeholder="Your Email *" data-sb-validations="required,email" />
                        <div class="invalid-feedback" data-sb-feedback="email:required">An email is required.</div>
                        <div class="invalid-feedback" data-sb-feedback="email:email">Email is not valid.</div>
                    </div>
                    <div class="form-group mb-md-0">
                        <!-- Phone number input-->
                        <input class="form-control" id="phone" type="tel" placeholder="Your Phone *" data-sb-validations="required" />
                        <div class="invalid-feedback" data-sb-feedback="phone:required">A phone number is required.</div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group form-group-textarea mb-md-0">
                        <!-- Message input-->
                        <textarea class="form-control" id="message" placeholder="Your Message *" data-sb-validations="required"></textarea>
                        <div class="invalid-feedback" data-sb-feedback="message:required">A message is required.</div>
                    </div>
                </div>
            </div>
            <!-- Submit success message-->
            <!---->
            <!-- This is what your users will see when the form-->
            <!-- has successfully submitted-->
            <div class="d-none" id="submitSuccessMessage">
                <div class="text-center text-white mb-3">
                    <div class="fw-bolder">Form submission successful!</div>
                    To activate this form, sign up at
                    <br />
                    <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                </div>
            </div>
            <!-- Submit error message-->
            <!---->
            <!-- This is what your users will see when there is-->
            <!-- an error submitting the form-->
            <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">Error sending message!</div></div>
            <!-- Submit Button-->
            <div class="text-center"><button class="btn btn-primary btn-xl text-uppercase disabled" id="submitButton" type="submit">Send Message</button></div>
        </form>
    </div>
</section>
<!-- Footer-->
<footer class="footer py-4">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-4 text-lg-start">Copyright &copy; Trip Me Travel 2023</div>
            <div class="col-lg-4 my-3 my-lg-0">
                <a class="btn btn-dark btn-social mx-2" href="{% url 'travelPages:twitter' %}" aria-label="Twitter"><i class="fab fa-twitter"></i></a>
                <a class="btn btn-dark btn-social mx-2" href="{% url 'travelPages:facebook' %}" aria-label="Facebook"><i class="fab fa-facebook-f"></i></a>
                <a class="btn btn-dark btn-social mx-2" href="{% url 'travelPages:linkedin' %}" aria-label="LinkedIn"><i class="fab fa-linkedin-in"></i></a>
            </div>
            <div class="col-lg-4 text-lg-end">
                <a class="link-dark text-decoration-none me-3" href="#!">Privacy Policy</a>
                <a class="link-dark text-decoration-none" href="#!">Terms of Use</a>
            </div>
        </div>
    </div>
</footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

templates/travelPages/details.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<meta name="description" content="A mock travel website, hosting trips to places that the author has been" />
<meta name="author" content="Preston Fitzgerald" />
{% if ti.country == "United States" %}
    <title>Trip to {{ti.city}}, {{ti.state}} | Trip Me Travel</title>   
{% else %}
    <title>Trip to {{ti.city}}, {{ti.country}} | Trip Me Travel</title>
{% endif %}
{% endblock %}

{% block nav %}
<div class="collapse navbar-collapse" id="navbarResponsive">
    <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
        <li class="nav-item"><a class="nav-link" href="{% url 'travelPages:index' %}">Home</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'travelPages:trips' %}">Vacations</a></li>
        <li class="nav-item"><a class="nav-link" href="#contact">Contact</a></li>
    </ul>
</div>
{% endblock %}

{% block Masthead %}
<header class="masthead" style="background-image: url('{% static "img/" %}{{ti.picture}}')" alt="{{ti.alt}}">
    <div class="container">
        <div class="masthead-subheading" style="text-shadow: 2px 2px black">Get ready to visit</div>
        <div class="masthead-heading text-uppercase" style="text-shadow: 2px 2px black">
            {% if ti.country == "United States" %}
                {{ti.city}}, {{ti.state}}
            {% else %}
                {{ti.city}}, {{ti.country}}
            {% endif %}
        </div>
        <a class="btn btn-primary btn-xl text-uppercase" href="#portfolio">Take me to {{ti.city}}</a>
    </div>
</header>
{% endblock %}

{% block content %}
<section class="page-section bg-light" id="portfolio">
    <div class="container">
        <div class="text-center">
            {% if ti.country == "United States" %}
                <h2 class="section-heading text-uppercase">{{ti.city}}, {{ti.state}}</h2>
            {% else %}
                <h2 class="section-heading text-uppercase">{{ti.city}}, {{ti.country}}</h2>
            {% endif %}
            <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>
            {{ti.description}}
            <br><br>
            <table class="table-center">
                <tr>
                    <td><b>City</b></td>
                    <td>{{ti.city}}</td>
                </tr>
                {% if ti.state != NULL %}
                <tr>
                    <td><b>State/province</b></td>
                    <td>{{ti.state}}</td>
                </tr>
                {% endif %}
                <tr>
                    <td><b>Country</b></td>
                    <td>{{ti.country}}</td>
                </tr>
                <tr>
                    <td><b>Cost</b></td>
                    <td>${{ti.cost}}</td>
                </tr>
                <tr>
                    <td><b>Number of days</b></td>
                    <td>{{ti.length}}</td>
                </tr>
            </table>
        </div>
    </div>
</section>
{% endblock %}

templates/travelPages/trips.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<meta name="description" content="A mock travel website, hosting trips to places that the author has been" />
<meta name="author" content="Preston Fitzgerald" />
<title>Available Trips | Trip Me Travel</title>
{% endblock %}
{% block nav %}
<div class="collapse navbar-collapse" id="navbarResponsive">
    <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
        <li class="nav-item"><a class="nav-link" href="{% url 'travelPages:index' %}">Home</a></li>
        <li class="nav-item"><a class="nav-link" href="#portfolio">Vacations</a></li>
        <li class="nav-item"><a class="nav-link" href="#contact">Contact</a></li>
    </ul>
</div>
{% endblock %}

{% block Masthead %}
<header class="masthead" style="background-image: url('{% static "img/new_river_bridge.jpg" %}')" alt="The New River Gorge Bridge as viewed from Long Point">
    <div class="container">
        <div class="masthead-subheading" style="text-shadow: 2px 2px black">Your One Stop to the Rest of the World</div>
        <div class="masthead-heading text-uppercase" style="text-shadow: 2px 2px black">Trip Me Travel</div>
        <a class="btn btn-primary btn-xl text-uppercase" href="#portfolio">Show Me the World</a>
    </div>
</header>
{% endblock %}

{% block content %}
<section class="page-section bg-light" id="portfolio">
    <div class="container">
        <div class="text-center">
            <h2 class="section-heading text-uppercase">Vacations</h2>
            <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>
        </div>
        <div class="row">
            {% for oTrips in ti %}
            <div class="col-lg-4 col-sm-6 mb-4">
                <!-- Portfolio item 1-->
                <div class="portfolio-item">
                    <a class="portfolio-link" data-bs-toggle="modal" href="#portfolioModal{{oTrips.id}}">
                        <div class="portfolio-hover">
                            <div class="portfolio-hover-content"><i class="fas fa-plus fa-3x"></i></div>
                        </div>
                        <img class="img-fluid" src="{% static 'img/' %}{{oTrips.picture}}" alt="{{oTrips.alt}}" />
                    </a>
                    <div class="portfolio-caption">
                        <div class="portfolio-caption-heading">{{oTrips.city}}</div>
                        {% if oTrips.country == "United States" %}
                        <div class="portfolio-caption-subheading text-muted">{{oTrips.state}}</div>
                        {% else %}
                        <div class="portfolio-caption-subheading text-muted">{{oTrips.country}}</div>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
<!-- Portfolio Modals-->
{% for oTrips in ti %}

<div class="portfolio-modal modal fade" id="portfolioModal{{oTrips.id}}" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="close-modal" data-bs-dismiss="modal"><img src="{% static 'img/close-icon.svg' %}" alt="Close modal" /></div>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-8">
                        <div class="modal-body">
                            <!-- Project details-->
                            <h2 class="text-uppercase">{{oTrips.city}}</h2>
                            <p class="item-intro text-muted">{% if oTrips.state == None %}
                                {{oTrips.country}}
                                {% else %}
                                {{oTrips.state}}, {{oTrips.country}}
                                {% endif %}</p>
                            <img class="img-fluid d-block mx-auto" src="{% static 'img/' %}{{oTrips.picture}}" alt="{{oTrips.alt}}" />
                            <p>{{oTrips.description}}</p>
                            <ul class="list-inline">
                                <li>
                                    <strong>Location:</strong>
                                    {% if oTrips.state == None %}
                                    {{oTrips.city}}
                                    {% else %}
                                    {{oTrips.city}}, {{oTrips.state}}
                                    {% endif %}
                                </li>
                                <li>
                                    <strong>Country:</strong>
                                    {{oTrips.country}}
                                </li>
                            </ul>
                            <a class="btn btn-primary btn-xl text-uppercase" href="{% url 'travelPages:details' id=oTrips.id %}">See more details</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endfor %}
{% endblock %}